version: '3'

services:
  domainsale:
    build:
      context: ..
      dockerfile: examples/Dockerfile
    container_name: domainsale
    command: example.com --format json
    # You can override the command when running with:
    # docker-compose run domainsale yourdomain.com --rdap --format html

  # Example of a web server using the domainsale package
  webserver:
    build:
      context: ..
      dockerfile: examples/Dockerfile
    container_name: domainsale-webserver
    ports:
      - "8000:8000"
    command: --server --host 0.0.0.0 --port 8000
    # This assumes the CLI has a --server option to run the web server
    # If not, you would need to create a custom Dockerfile for the web server
